//Account
export const ACCOUNT_ERROR = 'ACCOUNT_ERROR';
export const CLEAR_ACCOUNT_ERROR = 'CLEAR_ACCOUNT_ERROR';
export const LOG_IN = 'LOG_IN';
export const SIGN_UP = 'SIGN_UP';

//Feed
export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POSTS';
export const POST_ERROR = 'POST_ERROR';
export const CLEAR_POST_ERROR = 'CLEAR_POST_ERROR';
export const POST_START = 'POST_START';
export const POST_COMPLETE = 'POST_COMPLETE';
export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR';
export const CLEAR_EDIT_POST_ERROR = 'CLEAR_EDIT_POST_ERROR';
export const EDIT_POST_COMPLETE = 'EDIT_POST_COMPLETE';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const CLEAR_DELETE_POST_ERROR = 'CLEAR_DELETE_POST_ERROR';
export const DELETE_POST_COMPLETE = 'DELETE_POST_COMPLETE';

//Job
export const FETCH_JOBS = 'FETCH_JOBS';
export const NEW_JOB = 'NEW_JOBS';
export const JOB_ERROR = 'JOB_ERROR';
export const CLEAR_JOB_ERROR = 'CLEAR_JOB_ERROR';
export const JOB_START = 'JOB_START';
export const JOB_COMPLETE = 'JOB_COMPLETE';
export const EDIT_JOB = 'EDIT_JOB';
export const EDIT_JOB_START = 'EDIT_JOB_START';
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR';
export const CLEAR_EDIT_JOB_ERROR = 'CLEAR_EDIT_JOB_ERROR';
export const EDIT_JOB_COMPLETE = 'EDIT_JOB_COMPLETE';
export const DELETE_JOB = 'DELETE_JOB';
export const DELETE_JOB_START = 'DELETE_JOB_START';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';
export const CLEAR_DELETE_JOB_ERROR = 'CLEAR_DELETE_JOB_ERROR';
export const DELETE_JOB_COMPLETE = 'DELETE_JOB_COMPLETE';